services:
  db:
    image: postgres:16.3-alpine3.20
    container_name: postgresdb
    environment:
      - POSTGRES_PASSWORD = ${POSTGRES_PASSWORD}
      - POSTGRES_USER = ${POSTGRES_USER}
      - POSTGRES_DB = ${POSTGRES_DB}
    volumes:
      - ./services/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
  proxy:
    image: nginx:1.27.0-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./services/nginx:/etc/nginx/
  app:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./src:/opt/containership/src
    environment:
    - JWT_SECRET = ${JWT_SECRET}
    - POSTGRES_PASSWORD = ${POSTGRES_PASSWORD}
    - POSTGRES_USER = ${POSTGRES_USER}
    - POSTGRES_DB = ${POSTGRES_DB}
    - DOMAIN = ${DOMAIN}
    - IP = ${IP}
    - REGRU_USERNAME = ${REGRU_USERNAME}
    - REGRU_PASSWORD = ${REGRU_PASSWORD}
    env_file:
      - .env
    depends_on:
      - db
      - proxy